### ISSUE TITLE
Key Error 'einheitenaenderungnetzbetreiberzuordnungen'

### ISSUE THREAD

**Issue by AhmadShelbayeh** [OpenEnergyPlatform/open-MaStR#569]
## Description of the issue

Hey guys, I am getting a key error when downloading the Bulk data.
Code:
from open_mastr import Mastr
db = Mastr()
today_date = datetime.now().strftime('today')
db.download(method='bulk', data=["wind", "market", "permit", "deleted_units"], date=today_date)

KeyError: 'einheitenaenderungnetzbetreiberzuordnungen'

## Context and Environment
Version used: 0.14.3. and 0.14.4.
Environment setup and (python) version: 3.11. & 3.12.

**Comment by FlorianK13** [comment]
Hi @AhmadShelbayeh 
Based on [this code line](https://github.com/OpenEnergyPlatform/open-MaStR/blob/6bc72541135c8eac66ed6565794e238f5e157957/open_mastr/utils/orm.py#L941C6-L941C48) I assume that we have fixed this already. However a usual problem is that new versions of the database scheme are not initialized if an old database still exists. One solution should be that you delete your sqlite database (or the whole`~/.open-mastr` folder) and rerun your code. 

If this does not work, you can answer again in this issue.

**Comment by AhmadShelbayeh** [comment]
@FlorianK13 
Unfortunately, I deleted the entire folder and reran the code, but I am still encountering the same error. It seems the issue was not resolved by deleting the folder. Could you please help me troubleshoot this problem?

**Comment by AhmadShelbayeh** [comment]
@FlorianK13 

This is the error:

Download has started, this can take several minutes.The download bar is only a rough estimate.
C:\Users\ahmad.shelbayeh\.open-MaStR\data\xml_download\Gesamtdatenexport_20240930.zip: 19149 [09:20, 34.19/s]                               
Download is finished. It took 560 seconds.
MaStR was successfully downloaded to C:\Users\ahmad.shelbayeh\.open-MaStR\data\xml_download.
Table 'wind_eeg' is filled with data 'anlageneegwind' from the bulk download.
File 'AnlagenEegWind.xml' is parsed.
Data is cleansed.
Traceback (most recent call last):

  Cell In[1], line 13
    db.download(method='bulk', data=[

  File D:\Prog.cpy\Data\Anaconda3\envs\Ahmad\lib\site-packages\open_mastr\mastr.py:231 in download
    write_mastr_xml_to_database(

  File D:\Prog.cpy\Data\Anaconda3\envs\Ahmad\lib\site-packages\open_mastr\xml_download\utils_write_to_database.py:34 in write_mastr_xml_to_database
    if is_table_relevant(

  File D:\Prog.cpy\Data\Anaconda3\envs\Ahmad\lib\site-packages\open_mastr\xml_download\utils_write_to_database.py:76 in is_table_relevant
    tablename_mapping[xml_tablename]["__class__"] is not None

KeyError: 'einheitenaenderungnetzbetreiberzuordnungen'

**Comment by FlorianK13** [comment]
And your version right now is 0.14.4? Because 0.14.3 would initialize the old database schema.

**Comment by AhmadShelbayeh** [comment]
@FlorianK13 
How can I know my version, is it by run **pip install --upgrade open-mastr**, if yes my version is: 
open-mastr in d:\prog.cpy\data\anaconda3\envs\ahmad\lib\site-packages (0.14.1)
how can solve it?

**Comment by FlorianK13** [comment]
Then you need to run pip install --upgrade open-mastr

**Comment by AhmadShelbayeh** [comment]
@FlorianK13 
it works, thanks
